language: node_js
node_js:
- '12'
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
- npm install -g @angular/cli@7.3.9
script:
- ng lint
- npm run test-headless
- ng build --prod --base-href https://github.com/openMF/online-banking-app
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/project
  keep-history: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
