language: node_js
node_js:
  - "12"
dist: trusty
sudo: required
branches:
  only:
  - master
before_script:
  - npm install -g @angular/cli@7.3.9
script:
- ng lint
- npm run test-headless
- ng build --prod --base-href https://github.com/openMF/online-banking-app
secure: m42v5ut09dauxvvX5aAuN4khTFYZogV4BOvbI6ShKeNEI6foiox9ooRsY14m6MoSoDsV8XiHLqkhwMrJB3SjI1htZQFrTXesv7DJZNXJ1HBNnQOJB5UWY3CxWeCAX6JBTo+/5ZvIr7BPmhIWYWopM7aoNf6PrK8Y0kKl3YRmIj3LCWPyR/eqUdAciZpzHuaxOQkBkPPvlJeXLxaUiHW8dFPFebYP3GjALqpwPrL3PZUMovlxvFkSCvmpH3TlLxDI6IWgJJN4zIn6YLJ0GIQnFzxny5ZxDNokfu1y1gvraS88N0KDtom+t6YG9OC6grO+wYJTb/I6CDTnTPIaJw7dgnHXYQwimK8fDkFXEydmMc9JhCuGq1F0Y5+vc26Z9iVjbUlNZevElvtyxIAgbruPnKZtd3AHtSh+M5N8RLgZ4t0H1FQmIiljgfGGEf7ehHcEtRrsCPS/Vemzwz0XCNzQQNLSFxDDonGZEfnk4obu9SkF3pdltpnR9/D1jSaiJHuQEUMSm0pE2VCcyE92z9ne82TCpEjUbrnFGRBBGQYDkurfUMTrmyaAvnw0A2qwEAirYtSYsOx7TMSoTMCi38UE838FN287L7A0mW7Jw4vy8vFXzMsyAl3wWQBSW25sMK8NlnBHExvNmZP6sGNf7Vs1Hls4p7HfA5d6a/Uj8sLcz00=
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist/project
  keep-history: true
  github_token: m42v5ut09dauxvvX5aAuN4khTFYZogV4BOvbI6ShKeNEI6foiox9ooRsY14m6MoSoDsV8XiHLqkhwMrJB3SjI1htZQFrTXesv7DJZNXJ1HBNnQOJB5UWY3CxWeCAX6JBTo+/5ZvIr7BPmhIWYWopM7aoNf6PrK8Y0kKl3YRmIj3LCWPyR/eqUdAciZpzHuaxOQkBkPPvlJeXLxaUiHW8dFPFebYP3GjALqpwPrL3PZUMovlxvFkSCvmpH3TlLxDI6IWgJJN4zIn6YLJ0GIQnFzxny5ZxDNokfu1y1gvraS88N0KDtom+t6YG9OC6grO+wYJTb/I6CDTnTPIaJw7dgnHXYQwimK8fDkFXEydmMc9JhCuGq1F0Y5+vc26Z9iVjbUlNZevElvtyxIAgbruPnKZtd3AHtSh+M5N8RLgZ4t0H1FQmIiljgfGGEf7ehHcEtRrsCPS/Vemzwz0XCNzQQNLSFxDDonGZEfnk4obu9SkF3pdltpnR9/D1jSaiJHuQEUMSm0pE2VCcyE92z9ne82TCpEjUbrnFGRBBGQYDkurfUMTrmyaAvnw0A2qwEAirYtSYsOx7TMSoTMCi38UE838FN287L7A0mW7Jw4vy8vFXzMsyAl3wWQBSW25sMK8NlnBHExvNmZP6sGNf7Vs1Hls4p7HfA5d6a/Uj8sLcz00=
  on:
    branch: master